############################
## CHANGE THESE
############################

baseURL: "https://ivanlopez.info/hugo_qubt"
title: ivanlopez.info

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
