############################
## CHANGE THESE
############################

baseURL: "https://ivnlpz.github.io/hugo_qubt"
title: hugo_qubt

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
